name: inyourgut
favicon: null
layout_spectrum: 0.25857
typography_spectrum: 0.13341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.06505195517092943
  lightness: 0.923676619771868
  saturation: 0.8878206370864064
  rhythmicContrast: 0.601524293422699
purpose: []
